---
title: "FeaturesExample"
author: "George C. G. Barbosa"
date: "13 de setembro de 2016"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Importing Library's 
```{r import, warning=F}
library(openNLP)
library(NLP)
library(plyr)
```

### Sourcing Files + Loading Sentences
```{r source_load, warning=F, message=F}
setwd('/Users/ohack/segapp_v2/')
source(file = 'R/NLPTasks.R')
source(file = 'R/Patterns.R')
source(file = 'R/Extractions.R')
source(file = 'R/Util.R')
source(file = 'R/Graphs.R')
source(file = 'R/Features.R')

df_training <- readTrainingDF("data/nyt-extractions-all-labeled.txt", 200)
```

### Extract NLP Tags for each sentence
```{r extract_nlp, warning=F}
tags <- lapply(df_training, function(l){
  tag(l['rel'])
})

nlp_tags <- list()
for (i in 1:length(df_training)){
  tags_word <- tags[[i]][tags[[i]]$type=='word']
  nlp_tags[[i]] <- ext_nlp_tags(tags_word$features)
  rel <- as.String(df_training[[i]]['rel'])
  nlp_tags[[i]]$words <- rel[tags_word]
}
```

### Construct Features
```{r construct_features, warning=F}
library(knitr)
tags_f12 <- lapply(df_training, function(l){
  tag(l['sentence'])
})
features <- list(
  f1=f1(df_training), 
  f2=f_prep(nlp_tags, 'for'),
  f3=f_prep(nlp_tags, 'on'),
  f4=f_prep(nlp_tags, 'of'),
  f5=f_prep(nlp_tags, 'to'),
  f6=f_prep(nlp_tags, 'in'),
  f9=f9(df_training),
  f10=f10(df_training),
  f11=f11(df_training),
  f12=f12(tags_f12),
  y=sapply(df_training, function(l){ as.numeric(l[['y']]) })
)
features <- as.data.frame(features)
kable(features, caption = 'Features Construídas')
```
